// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5jdeSlJL7Ud0hZ2i4_Jf5iiu21lsEAg',
    appId: '1:168607691428:web:1cfc324c81c861e4c0ac31',
    messagingSenderId: '168607691428',
    projectId: 'budget-alert-20ced',
    authDomain: 'budget-alert-20ced.firebaseapp.com',
    storageBucket: 'budget-alert-20ced.appspot.com',
    measurementId: 'G-4WBBTY6KSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBNiy93E05GYAgR23tYyeFNPQ0TnYyDM',
    appId: '1:168607691428:android:3f3e3b3e67931ab9c0ac31',
    messagingSenderId: '168607691428',
    projectId: 'budget-alert-20ced',
    storageBucket: 'budget-alert-20ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAdHYTSPUTnUg7WAH88OoCqSj_PzVLylw',
    appId: '1:168607691428:ios:dbcde23fd20a97d8c0ac31',
    messagingSenderId: '168607691428',
    projectId: 'budget-alert-20ced',
    storageBucket: 'budget-alert-20ced.appspot.com',
    iosBundleId: 'com.example.budget_alert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAdHYTSPUTnUg7WAH88OoCqSj_PzVLylw',
    appId: '1:168607691428:ios:6b91141c02f872abc0ac31',
    messagingSenderId: '168607691428',
    projectId: 'budget-alert-20ced',
    storageBucket: 'budget-alert-20ced.appspot.com',
    iosBundleId: 'com.example.budget_alert.RunnerTests',
  );
}
